import asyncio
from abc import ABC, abstractmethod
from typing import Dict, Optional
from loguru import logger
from datetime import datetime

from ..core.event_engine import EventEngine, Event, EventType

class StrategyBase(ABC):
    """
    Abstract base class for trading strategies.
    """
    
    def __init__(self, name: str, event_engine: EventEngine, config: Dict = None):
        self.name = name
        self.event_engine = event_engine
        self.config = config or {}
        self.active = False
        
    async def start(self):
        """Start the strategy."""
        self.active = True
        self.event_engine.register(EventType.KLINE_UPDATE, self.on_kline_update)
        logger.info(f"Strategy {self.name} started")

    async def stop(self):
        """Stop the strategy."""
        self.active = False
        self.event_engine.unregister(EventType.KLINE_UPDATE, self.on_kline_update)
        logger.info(f"Strategy {self.name} stopped")

    @abstractmethod
    async def on_kline_update(self, event: Event):
        """Handle K-line updates."""
        pass

    async def send_signal(self, signal_type: str, direction: str, price: float, 
                         stop_loss: float = None, take_profit: float = None, 
                         reason: str = ""):
        """Emit a trading signal."""
        if not self.active:
            return
            
        signal_data = {
            "strategy": self.name,
            "type": signal_type,  # ENTRY, EXIT
            "direction": direction, # LONG, SHORT
            "price": price,
            "stop_loss": stop_loss,
            "take_profit": take_profit,
            "reason": reason,
            "timestamp": datetime.now()
        }
        
        event = Event(
            type=EventType.SIGNAL_GENERATED,
            data=signal_data,
            source=self.name
        )
        await self.event_engine.put(event)
        logger.info(f"Signal generated by {self.name}: {direction} @ {price}")
